// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package pgstore

import (
	"context"
)

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT email, password_hash
FROM admin
WHERE email = $1
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByEmail, email)
	var i Admin
	err := row.Scan(&i.Email, &i.PasswordHash)
	return i, err
}
