// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categoria.sql

package pgstore

import (
	"context"
)

const createCategoria = `-- name: CreateCategoria :one
INSERT INTO categoria (slug, nome, idade_minima, idade_maxima, descricao)
VALUES ($1, $2, $3, $4, $5)
RETURNING slug, nome, idade_minima, idade_maxima, descricao
`

type CreateCategoriaParams struct {
	Slug        string `json:"slug"`
	Nome        string `json:"nome"`
	IdadeMinima int32  `json:"idade_minima"`
	IdadeMaxima int32  `json:"idade_maxima"`
	Descricao   string `json:"descricao"`
}

func (q *Queries) CreateCategoria(ctx context.Context, arg CreateCategoriaParams) (Categorium, error) {
	row := q.db.QueryRow(ctx, createCategoria,
		arg.Slug,
		arg.Nome,
		arg.IdadeMinima,
		arg.IdadeMaxima,
		arg.Descricao,
	)
	var i Categorium
	err := row.Scan(
		&i.Slug,
		&i.Nome,
		&i.IdadeMinima,
		&i.IdadeMaxima,
		&i.Descricao,
	)
	return i, err
}

const deleteCategoria = `-- name: DeleteCategoria :exec
DELETE FROM categoria WHERE slug = $1
`

func (q *Queries) DeleteCategoria(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, deleteCategoria, slug)
	return err
}

const getCategoriaBySlug = `-- name: GetCategoriaBySlug :one
SELECT slug, nome, idade_minima, idade_maxima, descricao
FROM categoria
WHERE slug = $1
`

func (q *Queries) GetCategoriaBySlug(ctx context.Context, slug string) (Categorium, error) {
	row := q.db.QueryRow(ctx, getCategoriaBySlug, slug)
	var i Categorium
	err := row.Scan(
		&i.Slug,
		&i.Nome,
		&i.IdadeMinima,
		&i.IdadeMaxima,
		&i.Descricao,
	)
	return i, err
}

const listCategorias = `-- name: ListCategorias :many
SELECT slug, nome, idade_minima, idade_maxima, descricao
FROM categoria
ORDER BY idade_minima
`

func (q *Queries) ListCategorias(ctx context.Context) ([]Categorium, error) {
	rows, err := q.db.Query(ctx, listCategorias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Categorium
	for rows.Next() {
		var i Categorium
		if err := rows.Scan(
			&i.Slug,
			&i.Nome,
			&i.IdadeMinima,
			&i.IdadeMaxima,
			&i.Descricao,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategoria = `-- name: UpdateCategoria :one
UPDATE categoria
SET nome = $2, idade_minima = $3, idade_maxima = $4, descricao = $5
WHERE slug = $1
RETURNING slug, nome, idade_minima, idade_maxima, descricao
`

type UpdateCategoriaParams struct {
	Slug        string `json:"slug"`
	Nome        string `json:"nome"`
	IdadeMinima int32  `json:"idade_minima"`
	IdadeMaxima int32  `json:"idade_maxima"`
	Descricao   string `json:"descricao"`
}

func (q *Queries) UpdateCategoria(ctx context.Context, arg UpdateCategoriaParams) (Categorium, error) {
	row := q.db.QueryRow(ctx, updateCategoria,
		arg.Slug,
		arg.Nome,
		arg.IdadeMinima,
		arg.IdadeMaxima,
		arg.Descricao,
	)
	var i Categorium
	err := row.Scan(
		&i.Slug,
		&i.Nome,
		&i.IdadeMinima,
		&i.IdadeMaxima,
		&i.Descricao,
	)
	return i, err
}
