// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: equipe.sql

package pgstore

import (
	"context"
)

const createEquipe = `-- name: CreateEquipe :one
INSERT INTO equipe (slug, nome, cor, ano_fundacao, cidade)
VALUES ($1, $2, $3, $4, $5)
RETURNING slug, nome, cor, ano_fundacao, cidade
`

type CreateEquipeParams struct {
	Slug        string `json:"slug"`
	Nome        string `json:"nome"`
	Cor         string `json:"cor"`
	AnoFundacao int32  `json:"ano_fundacao"`
	Cidade      string `json:"cidade"`
}

func (q *Queries) CreateEquipe(ctx context.Context, arg CreateEquipeParams) (Equipe, error) {
	row := q.db.QueryRow(ctx, createEquipe,
		arg.Slug,
		arg.Nome,
		arg.Cor,
		arg.AnoFundacao,
		arg.Cidade,
	)
	var i Equipe
	err := row.Scan(
		&i.Slug,
		&i.Nome,
		&i.Cor,
		&i.AnoFundacao,
		&i.Cidade,
	)
	return i, err
}

const getEquipeBySlug = `-- name: GetEquipeBySlug :one
SELECT slug, nome, cor, ano_fundacao, cidade
FROM equipe
WHERE slug = $1
`

func (q *Queries) GetEquipeBySlug(ctx context.Context, slug string) (Equipe, error) {
	row := q.db.QueryRow(ctx, getEquipeBySlug, slug)
	var i Equipe
	err := row.Scan(
		&i.Slug,
		&i.Nome,
		&i.Cor,
		&i.AnoFundacao,
		&i.Cidade,
	)
	return i, err
}

const listEquipes = `-- name: ListEquipes :many
SELECT slug, nome, cor, ano_fundacao, cidade
FROM equipe
ORDER BY nome
`

func (q *Queries) ListEquipes(ctx context.Context) ([]Equipe, error) {
	rows, err := q.db.Query(ctx, listEquipes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Equipe
	for rows.Next() {
		var i Equipe
		if err := rows.Scan(
			&i.Slug,
			&i.Nome,
			&i.Cor,
			&i.AnoFundacao,
			&i.Cidade,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
