// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgstore

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Admin struct {
	Email        string `json:"email"`
	PasswordHash []byte `json:"password_hash"`
}

type Categorium struct {
	Slug        string `json:"slug"`
	Nome        string `json:"nome"`
	IdadeMinima int32  `json:"idade_minima"`
	IdadeMaxima int32  `json:"idade_maxima"`
	Descricao   string `json:"descricao"`
}

type Corrida struct {
	Slug          string      `json:"slug"`
	Nome          string      `json:"nome"`
	Data          pgtype.Date `json:"data"`
	Pista         string      `json:"pista"`
	CategoriaSlug string      `json:"categoria_slug"`
	Temporada     string      `json:"temporada"`
	Status        string      `json:"status"`
}

type Equipe struct {
	Slug        string `json:"slug"`
	Nome        string `json:"nome"`
	Cor         string `json:"cor"`
	AnoFundacao int32  `json:"ano_fundacao"`
	Cidade      string `json:"cidade"`
}

type Piloto struct {
	Cpf           string `json:"cpf"`
	Nome          string `json:"nome"`
	Slug          string `json:"slug"`
	Numero        int32  `json:"numero"`
	AnoNascimento int32  `json:"ano_nascimento"`
	Cidade        string `json:"cidade"`
	EquipeSlug    string `json:"equipe_slug"`
	CategoriaSlug string `json:"categoria_slug"`
}

type PilotoTemporada struct {
	PilotoCpf     string      `json:"piloto_cpf"`
	Temporada     string      `json:"temporada"`
	CategoriaSlug string      `json:"categoria_slug"`
	EquipeSlug    string      `json:"equipe_slug"`
	Pontos        int32       `json:"pontos"`
	Vitorias      int32       `json:"vitorias"`
	Podios        int32       `json:"podios"`
	MelhorVolta   pgtype.Text `json:"melhor_volta"`
	Posicao       int32       `json:"posicao"`
}

type ResultadoCorrida struct {
	CorridaSlug string `json:"corrida_slug"`
	Posicao     int32  `json:"posicao"`
	PilotoCpf   string `json:"piloto_cpf"`
	EquipeSlug  string `json:"equipe_slug"`
	MelhorVolta string `json:"melhor_volta"`
	TempoTotal  string `json:"tempo_total"`
	Pontos      int32  `json:"pontos"`
}
