// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: piloto.sql

package pgstore

import (
	"context"
)

const createPiloto = `-- name: CreatePiloto :one
INSERT INTO piloto (cpf, nome, slug, numero, ano_nascimento, cidade, equipe_slug, categoria_slug)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING cpf, nome, slug, numero, ano_nascimento, cidade, equipe_slug, categoria_slug
`

type CreatePilotoParams struct {
	Cpf           string `json:"cpf"`
	Nome          string `json:"nome"`
	Slug          string `json:"slug"`
	Numero        int32  `json:"numero"`
	AnoNascimento int32  `json:"ano_nascimento"`
	Cidade        string `json:"cidade"`
	EquipeSlug    string `json:"equipe_slug"`
	CategoriaSlug string `json:"categoria_slug"`
}

func (q *Queries) CreatePiloto(ctx context.Context, arg CreatePilotoParams) (Piloto, error) {
	row := q.db.QueryRow(ctx, createPiloto,
		arg.Cpf,
		arg.Nome,
		arg.Slug,
		arg.Numero,
		arg.AnoNascimento,
		arg.Cidade,
		arg.EquipeSlug,
		arg.CategoriaSlug,
	)
	var i Piloto
	err := row.Scan(
		&i.Cpf,
		&i.Nome,
		&i.Slug,
		&i.Numero,
		&i.AnoNascimento,
		&i.Cidade,
		&i.EquipeSlug,
		&i.CategoriaSlug,
	)
	return i, err
}

const deletePiloto = `-- name: DeletePiloto :exec
DELETE FROM piloto WHERE cpf = $1
`

func (q *Queries) DeletePiloto(ctx context.Context, cpf string) error {
	_, err := q.db.Exec(ctx, deletePiloto, cpf)
	return err
}

const getPilotoByCpf = `-- name: GetPilotoByCpf :one
SELECT cpf, nome, slug, numero, ano_nascimento, cidade, equipe_slug, categoria_slug
FROM piloto
WHERE cpf = $1
`

func (q *Queries) GetPilotoByCpf(ctx context.Context, cpf string) (Piloto, error) {
	row := q.db.QueryRow(ctx, getPilotoByCpf, cpf)
	var i Piloto
	err := row.Scan(
		&i.Cpf,
		&i.Nome,
		&i.Slug,
		&i.Numero,
		&i.AnoNascimento,
		&i.Cidade,
		&i.EquipeSlug,
		&i.CategoriaSlug,
	)
	return i, err
}

const getPilotoBySlug = `-- name: GetPilotoBySlug :one
SELECT cpf, nome, slug, numero, ano_nascimento, cidade, equipe_slug, categoria_slug
FROM piloto
WHERE slug = $1
`

func (q *Queries) GetPilotoBySlug(ctx context.Context, slug string) (Piloto, error) {
	row := q.db.QueryRow(ctx, getPilotoBySlug, slug)
	var i Piloto
	err := row.Scan(
		&i.Cpf,
		&i.Nome,
		&i.Slug,
		&i.Numero,
		&i.AnoNascimento,
		&i.Cidade,
		&i.EquipeSlug,
		&i.CategoriaSlug,
	)
	return i, err
}

const listPilotos = `-- name: ListPilotos :many
SELECT cpf, nome, slug, numero, ano_nascimento, cidade, equipe_slug, categoria_slug
FROM piloto
ORDER BY nome
`

func (q *Queries) ListPilotos(ctx context.Context) ([]Piloto, error) {
	rows, err := q.db.Query(ctx, listPilotos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Piloto
	for rows.Next() {
		var i Piloto
		if err := rows.Scan(
			&i.Cpf,
			&i.Nome,
			&i.Slug,
			&i.Numero,
			&i.AnoNascimento,
			&i.Cidade,
			&i.EquipeSlug,
			&i.CategoriaSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPilotosByCategoria = `-- name: ListPilotosByCategoria :many
SELECT cpf, nome, slug, numero, ano_nascimento, cidade, equipe_slug, categoria_slug
FROM piloto
WHERE categoria_slug = $1
ORDER BY nome
`

func (q *Queries) ListPilotosByCategoria(ctx context.Context, categoriaSlug string) ([]Piloto, error) {
	rows, err := q.db.Query(ctx, listPilotosByCategoria, categoriaSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Piloto
	for rows.Next() {
		var i Piloto
		if err := rows.Scan(
			&i.Cpf,
			&i.Nome,
			&i.Slug,
			&i.Numero,
			&i.AnoNascimento,
			&i.Cidade,
			&i.EquipeSlug,
			&i.CategoriaSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPilotosByEquipe = `-- name: ListPilotosByEquipe :many
SELECT cpf, nome, slug, numero, ano_nascimento, cidade, equipe_slug, categoria_slug
FROM piloto
WHERE equipe_slug = $1
ORDER BY nome
`

func (q *Queries) ListPilotosByEquipe(ctx context.Context, equipeSlug string) ([]Piloto, error) {
	rows, err := q.db.Query(ctx, listPilotosByEquipe, equipeSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Piloto
	for rows.Next() {
		var i Piloto
		if err := rows.Scan(
			&i.Cpf,
			&i.Nome,
			&i.Slug,
			&i.Numero,
			&i.AnoNascimento,
			&i.Cidade,
			&i.EquipeSlug,
			&i.CategoriaSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePiloto = `-- name: UpdatePiloto :one
UPDATE piloto
SET nome = $2, slug = $3, numero = $4, ano_nascimento = $5, cidade = $6, equipe_slug = $7, categoria_slug = $8
WHERE cpf = $1
RETURNING cpf, nome, slug, numero, ano_nascimento, cidade, equipe_slug, categoria_slug
`

type UpdatePilotoParams struct {
	Cpf           string `json:"cpf"`
	Nome          string `json:"nome"`
	Slug          string `json:"slug"`
	Numero        int32  `json:"numero"`
	AnoNascimento int32  `json:"ano_nascimento"`
	Cidade        string `json:"cidade"`
	EquipeSlug    string `json:"equipe_slug"`
	CategoriaSlug string `json:"categoria_slug"`
}

func (q *Queries) UpdatePiloto(ctx context.Context, arg UpdatePilotoParams) (Piloto, error) {
	row := q.db.QueryRow(ctx, updatePiloto,
		arg.Cpf,
		arg.Nome,
		arg.Slug,
		arg.Numero,
		arg.AnoNascimento,
		arg.Cidade,
		arg.EquipeSlug,
		arg.CategoriaSlug,
	)
	var i Piloto
	err := row.Scan(
		&i.Cpf,
		&i.Nome,
		&i.Slug,
		&i.Numero,
		&i.AnoNascimento,
		&i.Cidade,
		&i.EquipeSlug,
		&i.CategoriaSlug,
	)
	return i, err
}
