// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: piloto_temporada.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPilotoTemporada = `-- name: CreatePilotoTemporada :one
INSERT INTO piloto_temporada (piloto_cpf, temporada, categoria_slug, equipe_slug, pontos, vitorias, podios, melhor_volta, posicao)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING piloto_cpf, temporada, categoria_slug, equipe_slug, pontos, vitorias, podios, melhor_volta, posicao
`

type CreatePilotoTemporadaParams struct {
	PilotoCpf     string      `json:"piloto_cpf"`
	Temporada     string      `json:"temporada"`
	CategoriaSlug string      `json:"categoria_slug"`
	EquipeSlug    string      `json:"equipe_slug"`
	Pontos        int32       `json:"pontos"`
	Vitorias      int32       `json:"vitorias"`
	Podios        int32       `json:"podios"`
	MelhorVolta   pgtype.Text `json:"melhor_volta"`
	Posicao       int32       `json:"posicao"`
}

func (q *Queries) CreatePilotoTemporada(ctx context.Context, arg CreatePilotoTemporadaParams) (PilotoTemporada, error) {
	row := q.db.QueryRow(ctx, createPilotoTemporada,
		arg.PilotoCpf,
		arg.Temporada,
		arg.CategoriaSlug,
		arg.EquipeSlug,
		arg.Pontos,
		arg.Vitorias,
		arg.Podios,
		arg.MelhorVolta,
		arg.Posicao,
	)
	var i PilotoTemporada
	err := row.Scan(
		&i.PilotoCpf,
		&i.Temporada,
		&i.CategoriaSlug,
		&i.EquipeSlug,
		&i.Pontos,
		&i.Vitorias,
		&i.Podios,
		&i.MelhorVolta,
		&i.Posicao,
	)
	return i, err
}

const deletePilotoTemporada = `-- name: DeletePilotoTemporada :exec
DELETE FROM piloto_temporada WHERE piloto_cpf = $1 AND temporada = $2 AND categoria_slug = $3
`

type DeletePilotoTemporadaParams struct {
	PilotoCpf     string `json:"piloto_cpf"`
	Temporada     string `json:"temporada"`
	CategoriaSlug string `json:"categoria_slug"`
}

func (q *Queries) DeletePilotoTemporada(ctx context.Context, arg DeletePilotoTemporadaParams) error {
	_, err := q.db.Exec(ctx, deletePilotoTemporada, arg.PilotoCpf, arg.Temporada, arg.CategoriaSlug)
	return err
}

const getPilotoTemporada = `-- name: GetPilotoTemporada :one
SELECT piloto_cpf, temporada, categoria_slug, equipe_slug, pontos, vitorias, podios, melhor_volta, posicao
FROM piloto_temporada
WHERE piloto_cpf = $1 AND temporada = $2 AND categoria_slug = $3
`

type GetPilotoTemporadaParams struct {
	PilotoCpf     string `json:"piloto_cpf"`
	Temporada     string `json:"temporada"`
	CategoriaSlug string `json:"categoria_slug"`
}

func (q *Queries) GetPilotoTemporada(ctx context.Context, arg GetPilotoTemporadaParams) (PilotoTemporada, error) {
	row := q.db.QueryRow(ctx, getPilotoTemporada, arg.PilotoCpf, arg.Temporada, arg.CategoriaSlug)
	var i PilotoTemporada
	err := row.Scan(
		&i.PilotoCpf,
		&i.Temporada,
		&i.CategoriaSlug,
		&i.EquipeSlug,
		&i.Pontos,
		&i.Vitorias,
		&i.Podios,
		&i.MelhorVolta,
		&i.Posicao,
	)
	return i, err
}

const listPilotoTemporadaByPiloto = `-- name: ListPilotoTemporadaByPiloto :many
SELECT piloto_cpf, temporada, categoria_slug, equipe_slug, pontos, vitorias, podios, melhor_volta, posicao
FROM piloto_temporada
WHERE piloto_cpf = $1
ORDER BY temporada DESC, categoria_slug
`

func (q *Queries) ListPilotoTemporadaByPiloto(ctx context.Context, pilotoCpf string) ([]PilotoTemporada, error) {
	rows, err := q.db.Query(ctx, listPilotoTemporadaByPiloto, pilotoCpf)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PilotoTemporada
	for rows.Next() {
		var i PilotoTemporada
		if err := rows.Scan(
			&i.PilotoCpf,
			&i.Temporada,
			&i.CategoriaSlug,
			&i.EquipeSlug,
			&i.Pontos,
			&i.Vitorias,
			&i.Podios,
			&i.MelhorVolta,
			&i.Posicao,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStandingsByCategoriaAndTemporada = `-- name: ListStandingsByCategoriaAndTemporada :many
SELECT piloto_cpf, temporada, categoria_slug, equipe_slug, pontos, vitorias, podios, melhor_volta, posicao
FROM piloto_temporada
WHERE categoria_slug = $1 AND temporada = $2
ORDER BY posicao
`

type ListStandingsByCategoriaAndTemporadaParams struct {
	CategoriaSlug string `json:"categoria_slug"`
	Temporada     string `json:"temporada"`
}

func (q *Queries) ListStandingsByCategoriaAndTemporada(ctx context.Context, arg ListStandingsByCategoriaAndTemporadaParams) ([]PilotoTemporada, error) {
	rows, err := q.db.Query(ctx, listStandingsByCategoriaAndTemporada, arg.CategoriaSlug, arg.Temporada)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PilotoTemporada
	for rows.Next() {
		var i PilotoTemporada
		if err := rows.Scan(
			&i.PilotoCpf,
			&i.Temporada,
			&i.CategoriaSlug,
			&i.EquipeSlug,
			&i.Pontos,
			&i.Vitorias,
			&i.Podios,
			&i.MelhorVolta,
			&i.Posicao,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePilotoTemporada = `-- name: UpdatePilotoTemporada :one
UPDATE piloto_temporada
SET equipe_slug = $4, pontos = $5, vitorias = $6, podios = $7, melhor_volta = $8, posicao = $9
WHERE piloto_cpf = $1 AND temporada = $2 AND categoria_slug = $3
RETURNING piloto_cpf, temporada, categoria_slug, equipe_slug, pontos, vitorias, podios, melhor_volta, posicao
`

type UpdatePilotoTemporadaParams struct {
	PilotoCpf     string      `json:"piloto_cpf"`
	Temporada     string      `json:"temporada"`
	CategoriaSlug string      `json:"categoria_slug"`
	EquipeSlug    string      `json:"equipe_slug"`
	Pontos        int32       `json:"pontos"`
	Vitorias      int32       `json:"vitorias"`
	Podios        int32       `json:"podios"`
	MelhorVolta   pgtype.Text `json:"melhor_volta"`
	Posicao       int32       `json:"posicao"`
}

func (q *Queries) UpdatePilotoTemporada(ctx context.Context, arg UpdatePilotoTemporadaParams) (PilotoTemporada, error) {
	row := q.db.QueryRow(ctx, updatePilotoTemporada,
		arg.PilotoCpf,
		arg.Temporada,
		arg.CategoriaSlug,
		arg.EquipeSlug,
		arg.Pontos,
		arg.Vitorias,
		arg.Podios,
		arg.MelhorVolta,
		arg.Posicao,
	)
	var i PilotoTemporada
	err := row.Scan(
		&i.PilotoCpf,
		&i.Temporada,
		&i.CategoriaSlug,
		&i.EquipeSlug,
		&i.Pontos,
		&i.Vitorias,
		&i.Podios,
		&i.MelhorVolta,
		&i.Posicao,
	)
	return i, err
}
